### ISSUE TITLE
Version of pytorch used in the code

### ISSUE THREAD

**Issue by Tianchen627** [RichardHGL/UPGAN#3]
Mine is 1.2.0，I get the error below:

```
..\torch\csrc\autograd\python_anomaly_mode.cpp:57: UserWarning: Traceback of forward call that caused the error:
  File "main_pretrain.py", line 152, in <module>
    main()
  File "main_pretrain.py", line 142, in main
    trainer.train(0, args.n_epochs - 1)
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 76, in train
    train_loss, pos_loss, neg_loss = self.train_epoch_kg()
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 154, in train_epoch_kg
    pretrain=False)
  File "F:\UPGAN\UPGAN-master\Model\base_model.py", line 129, in fetch_user_batch
    hop_rep = self.query_layer.forward_kg(tp_rep, tail_rep, edge_list_hop, requires_grad=False)
  File "F:\UPGAN\UPGAN-master\Model\layers.py", line 163, in forward_kg
    rel_edge_list, rel_list, requires_grad=requires_grad)
  File "F:\UPGAN\UPGAN-master\Model\layers.py", line 148, in forward
    h_prime = torch.sparse.mm(sp_edge_e, tail_val)  # entity_rep_all
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\sparse\__init__.py", line 67, in mm
    return torch._sparse_mm(mat1, mat2)

Traceback (most recent call last):
  File "main_pretrain.py", line 152, in <module>
    main()
  File "main_pretrain.py", line 142, in main
    trainer.train(0, args.n_epochs - 1)
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 76, in train
    train_loss, pos_loss, neg_loss = self.train_epoch_kg()
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 161, in train_epoch_kg
    loss, loss_pos, loss_neg = self.dis_step(heads, rels, tails, neg_tails, sample_weight, user_rep)
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 121, in dis_step
    loss.backward()
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "E:\anaconda\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: No function is registered for schema aten::ne(Tensor self, Tensor other) -> Tensor on backend SparseCUDA
```

As  far as I know,this problem may be caused by the inplace operation of pytorch.I have tried my best but I can't make it work.

**Comment by RichardHGL** [comment]
I used 1.3.0 or 1.3.1. You can update the pytorch version.

**Comment by Tianchen627** [comment]
> I used 1.3.0 or 1.3.1. You can update the pytorch version.

Now it works well on 1.3.0.
thx!
